steps:
  - command: "script/build"
    label: "build/deploy staging"
    agents:
    - "region=us-west-2"
    branches: "staging"

  - command: "script/build"
    label: "build/deploy production"
    agents:
    - "region=us-west-2"
    branches: "master"
