steps:
  - command: "script/build"
    label: "build/deploy staging"
    agents:
    - "region=us-west-2"
    branches: "main"
    plugins:
      - ecr#v2.1.1:
          login: true
          region: "us-east-1"

  - command: "script/build"
    label: "build/deploy production"
    agents:
    - "region=us-west-2"
    branches: "master"
    plugins:
      - ecr#v2.1.1:
          login: true
          region: "us-east-1"